#Vikas Bansal 10 Aug 2020 #All  samples
#Foundin project. Raw expression matrix were generated by cellRanger pipeline using FOUNDIN GTF.

set.seed(786)
setwd("/data/vikas/FOUNDIN_scRNA/")

library(Seurat)
library(devtools)
library(ggplot2)
library(cowplot)

library(dplyr)
library(readxl)

library(stringi)
library(purrr)
library(reshape)
library(data.table)


pathto.outPlots <- "/data/vikas/FOUNDIN_scRNA/OutputPlots/iPSCsDopaALL/"
pathto.outData <- "/data/vikas/FOUNDIN_scRNA/OutputData/iPSCsDopaALL/"
outName <- "iPSCsDopaALL"

dirs <- list.dirs(path="/data/vikas/FOUNDIN_scRNA/CellRanger_Counts/")

Gene_results_file_names <- dirs[ grepl("filtered_feature_bc_matrix", dirs) ]



test_data <- Read10X(data.dir = Gene_results_file_names[1])


Sample_name <- unlist(strsplit(Gene_results_file_names[1],"/"))[[7]]

ALL_WITH_COUNT <- as.data.frame(test_data)

colnames(ALL_WITH_COUNT) <- paste(colnames(ALL_WITH_COUNT),Sample_name, sep="_")

All_joined_countMatrixTemp <- (ALL_WITH_COUNT)

for (i in 2:length(Gene_results_file_names)){
  cat("loop", i, "\n")


  test_data <- Read10X(data.dir = Gene_results_file_names[i])


  Sample_name <- unlist(strsplit(Gene_results_file_names[i],"/"))[[7]]

  ALL_WITH_COUNT <- as.data.frame(test_data)

  colnames(ALL_WITH_COUNT) <- paste(colnames(ALL_WITH_COUNT),Sample_name, sep="_")


  All_joined_countMatrix <- cbind(All_joined_countMatrixTemp,ALL_WITH_COUNT)

  All_joined_countMatrixTemp <- All_joined_countMatrix
}




metaDataOurs <-  data.frame(matrix(nrow=ncol(All_joined_countMatrix),ncol=2))

metaDataOurs[,1] <- colnames(All_joined_countMatrix)

metaDataOurs[,2] <- (sapply(stri_split_fixed(str = metaDataOurs[,1], pattern = "_", n = 2),"[[",2))

colnames(metaDataOurs)[1] <- "WholeID"
colnames(metaDataOurs)[2] <- "SampleID"


Petertable <- read_excel("MetaInfo/Samples_names_codes_final_vikas.xlsx", sheet = 1)

Petertablev2 <- (as.data.frame(Petertable))
Petertablev3 <- Petertablev2[grep("CDI",Petertablev2[,"Barcode_DZNE"]),]


Petertablev3$Barcode_last4 <- (stri_sub(Petertablev3$Barcode_DZNE,-4,-1))

Petertablev3$SampleID <- (paste0("SCRN_PPMI",Petertablev3$PPMI_ID, "_", Petertablev3$Barcode_last4,"_da65"))

Petertablev4 <- Petertablev3
Petertablev4[c(nrow(Petertablev3)+1,nrow(Petertablev3)+2,nrow(Petertablev3)+3),] <- Petertablev3[grep("SCRN_PPMI3966_2813_da65",Petertablev3$SampleID),]

Petertablev4[c(nrow(Petertablev3)+1,nrow(Petertablev3)+2,nrow(Petertablev3)+3),"SampleID"] <- c('SCRN_PPMI3966B3_2813_da65', 'SCRN_PPMI3966E6_2813_da65', 'SCRN_PPMI3966E8_2813_da65')
Petertablev4[grep("SCRN_PPMI3966B3_2813_da65",Petertablev4$SampleID),"BATCH"] <- 3
Petertablev4[grep("SCRN_PPMI3966E6_2813_da65",Petertablev4$SampleID),"BATCH"] <- 5
Petertablev4[grep("SCRN_PPMI3966E8_2813_da65",Petertablev4$SampleID),"BATCH"] <- 5

metaInfoAll <- (merge(metaDataOurs, Petertablev4, by="SampleID"))

rownames(metaInfoAll) <- metaInfoAll$WholeID


rm(list = c('test_data','ALL_WITH_COUNT','All_joined_countMatrixTemp','metaDataOurs'))




####If memeory is the issue################################################################
#df1 <- All_joined_countMatrix[,1:200000]
#df2 <- All_joined_countMatrix[,200001:400000]
#df3 <- All_joined_countMatrix[,400001:ncol(All_joined_countMatrix)]

#iPSCsDopaDf1 <- CreateSeuratObject(df1, meta.data = metaInfoAll, min.cells = 100, min.features = 1000)
#iPSCsDopaDf2 <- CreateSeuratObject(df2, meta.data = metaInfoAll, min.cells = 100, min.features = 1000)
#iPSCsDopaDf3 <- CreateSeuratObject(df3, meta.data = metaInfoAll, min.cells = 100, min.features = 1000)

#iPSCsDopaM1 <- merge(iPSCsDopaDf1, y = iPSCsDopaDf2)
#iPSCsDopa <- merge(iPSCsDopaM1, y = iPSCsDopaDf3)
######################################################################

iPSCsDopa <- CreateSeuratObject(All_joined_countMatrix, meta.data = metaInfoAll, min.cells = 100, min.features = 1000)

rm(list = c('test_data','All_joined_countMatrix','ALL_WITH_COUNT','All_joined_countMatrixTemp','metaDataOurs'))


iPSCsDopa[["percent.mt"]] <- PercentageFeatureSet(iPSCsDopa, pattern = "^MT-")


#VlnPlot(iPSCsDopa, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)


plot1 <- FeatureScatter(iPSCsDopa, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(iPSCsDopa, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

pdf(paste0(pathto.outPlots,"nCountPercentMT_scatter.pdf"), width=10, height=10)
CombinePlots(plots = list(plot1, plot2))
dev.off()

plot1 <- FeatureScatter(iPSCsDopa, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(iPSCsDopa, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")

png(paste0(pathto.outPlots,"nCountPercentMT_scatter.png"), width=2000, height=1000)
CombinePlots(plots = list(plot1, plot2))
dev.off()

saveRDS(iPSCsDopa,file = paste0(pathto.outData,outName,"_iPSCsDopa.initial.RDS"))



#iPSCsDopa <- readRDS(paste0(pathto.outData,outName,"_iPSCsDopa.initial.RDS"))

iPSCsDopa <- subset(iPSCsDopa, subset =  percent.mt < 20 & nFeature_RNA < 9000)

iPSCsDopa.list <- SplitObject(iPSCsDopa, split.by = "SampleID")





for (i in 1:length(iPSCsDopa.list)) {
  iPSCsDopa.list[[i]] <- SCTransform(iPSCsDopa.list[[i]])
}


iPSCsDopa.features <- SelectIntegrationFeatures(object.list = iPSCsDopa.list, nfeatures = 3000)
iPSCsDopa.list <- PrepSCTIntegration(object.list = iPSCsDopa.list, anchor.features = iPSCsDopa.features)





reference.list <- iPSCsDopa.list[unique(iPSCsDopa$SampleID)]

#Take all dataset with highest number of cells
reference_dataset <- match(names(tail(sort(table(iPSCsDopa$SampleID)),3)),names(reference.list))

iPSCsDopa.anchors <- FindIntegrationAnchors(object.list = iPSCsDopa.list, normalization.method = "SCT",
                                            anchor.features = iPSCsDopa.features, reference = reference_dataset)

saveRDS(iPSCsDopa.anchors,file = paste0(pathto.outData,outName,"_iPSCsDopa.anchors.RDS"))

#iPSCsDopa.anchors <- readRDS(file = paste0(pathto.outData,outName,"_iPSCsDopa.anchors.RDS"))


#rm(list = c('iPSCsDopa','iPSCsDopa.list','reference.list'))

#rm(list=ls())

iPSCsDopa.integrated <- IntegrateData(anchorset = iPSCsDopa.anchors, normalization.method = "SCT")

rm(list = c('iPSCsDopa','iPSCsDopa.anchors','iPSCsDopa.list','reference.list'))

iPSCsDopa.integrated <- RunPCA(iPSCsDopa.integrated, npcs = 30)

#iPSCsDopa.integrated <- RunTSNE(iPSCsDopa.integrated, nthreads = 40, max_iter = 2000, dims = 1:30)


iPSCsDopa.integrated <- RunUMAP(iPSCsDopa.integrated, dims = 1:30)

DefaultAssay(iPSCsDopa.integrated) <- "integrated"

iPSCsDopa.integrated <- FindNeighbors(iPSCsDopa.integrated, reduction = "pca", dims = 1:30, nn.eps = 0.5)
iPSCsDopa.integrated <- FindClusters(iPSCsDopa.integrated, resolution = 0.1, n.start = 10)


iPSCsDopa.integrated <- FindNeighbors(iPSCsDopa.integrated, reduction = "pca", dims = 1:30, nn.eps = 0.5)
iPSCsDopa.integrated <- FindClusters(iPSCsDopa.integrated, resolution = 0.2, n.start = 10)


p2 <- DimPlot(iPSCsDopa.integrated, reduction = "umap", label = TRUE)


png(paste(pathto.outPlots,"UMAP_integratedRes0.2.png"), width=1000, height=1000)
plot_grid(p2)
dev.off()


png(paste(pathto.outPlots,"UMAP_integratedClusterSplit.png"), width=2000, height=2000)
DimPlot(iPSCsDopa.integrated, reduction = "umap", label = TRUE, pt.size = 2, split.by = "seurat_clusters", ncol=4)
dev.off()

DefaultAssay(iPSCsDopa.integrated) <- "RNA"

iPSCsDopa.integrated <- NormalizeData(iPSCsDopa.integrated, verbose = FALSE)

DefaultAssay(iPSCsDopa.integrated) <- "integrated"

saveRDS(iPSCsDopa.integrated,file = paste0(pathto.outData,outName,"_iPSCsDopa.integrated.RDS"))
